### ISSUE TITLE
Document sslmode (ERROR: no pg_hba.conf entry for host...)

### ISSUE THREAD

**Issue by oliverpool** [pgRITA/node-pgrita#1]
I just tested your tool on a database hosted on heroku (using the connection string thay provider `postgres://user:pwd@host:5432/database`).

This initially failed with:
```
ERROR: no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "***, database "***", SSL off
```

To attempt to fix this, I first added `?ssl=true` to the connection string, which failed with:
```
ERROR: self signed certificate
```

And then I replaced it with `?ssl=no-verify` which did the trick!

Final URL: `postgres://user:pwd@host:5432/database?ssl=no-verify`

Those settings are actually managed by the [`pg`](https://www.npmjs.com/package/pg) dependency, but I think it would be nice for your users to have this mentioned somewhere, to get started even faster :-)

---
I have been using Hasura on my latest project and just discovered your wonderful galaxy of projects!

pgRITA found some issues in the internal schema (hdb_catalog) of hasura ;-)

Your documentation and open-source work is so impressive, that I will give graphile a try for my next project :smile: and want to support it :-)

**Comment by benjie** [comment]
@oliverpool Ah yes; thanks for raising this. It was actually me who wrote [the fix for `pg`](https://github.com/brianc/node-postgres/pull/2345) that allowed `?sslmode=no-verify` :raised_hands: I'll get this addressed in the next few weeks. And thanks for your kind words :heart:
