### ISSUE TITLE
pgrita introspection uploading seems not to work

### ISSUE THREAD

**Issue by wanradt** [pgRITA/node-pgrita#2]
Hi!

Tried to introspect my DB, with `npx` and `bash`, both exit with an error:

```
[pgRITA] introspecting database
[pgRITA] uploading introspection results
[pgRITA] Something went wrong uploading/analyzing your snapshot; details follow:

ERROR: Snapshot failed to run - perhaps there was something wrong with the upload?

{ message: 'processing failed' }

For details, visit:

https://pgrita.com/o/[my_org]/p/kiikaja/5

```
Details on URL above:

![image](https://github.com/user-attachments/assets/67f41d5e-1a8e-4601-8789-be387a529d1f)

Tried to run the introspection query, it seems work fine and gives big JSON blob.

Tried running `curl` manually from CLI, same result.

**Comment by benjie** [comment]
Thanks for the report; I’ll look into this next week. What version of PostgreSQL are you running, and do you have any interesting extensions installed?

**Comment by wanradt** [comment]
Version is 9.6 and the introspection query runs fine, TEMP-files are created but the problem occurs while trying to upload the file. As mentioned, tried every step manually, uploading is the first failure.

No third party extensions, `hstore` is one not default I can recall.

Edit. looked for extensions:
         "extname" : "hstore",
         "extname" : "hstore_plperl",
         "extname" : "pgcrypto",
         "extname" : "pg_trgm",
         "extname" : "plperl"
         "extname" : "plpgsql"

Thank you for looking into.

Wbr,

Gunnar

**Comment by benjie** [comment]
I'm afraid Postgres 9.6 is likely too old for pgRITA; the last release of Postgres 9.6 was November 2021 and it's no longer supported by Postgres - you can see the supported versions here: https://www.postgresql.org/support/versioning/

I can confirm pgRITA seems to be working correctly with PG 13 and PG 16 at least.

**Comment by benjie** [comment]
(If memory serves, Postgres v10 is the lowest version pgRITA might work with, but we officially only support supported versions of Postgres.)

**Comment by wanradt** [comment]
Thank you looking into, will try again after upgrade.
